/**
 * SENT Tokenizer - TypeScript port of src/tokenizers/sent decode logic.
 *
 * Decodes token sequences generated by the MOSAIC GPT-2 model (SENT variant)
 * back into molecular graph structures (atoms, bonds).
 *
 * SENT is a flat walk-based tokenizer (no communities/super-graph).
 *
 * Token vocabulary:
 *   0: SOS, 1: RESET, 2: LADJ, 3: RADJ, 4: EOS, 5: PAD
 *   6+: Node indices (offset by IDX_OFFSET)
 *
 * For labeled graphs, vocab layout:
 *   [special (6)] + [node IDs (max_num_nodes)] + [atom types (10)] + [bond types (5)]
 *
 * Labeled SENT sequence format (after SOS, before EOS):
 *   node0 node_label0 [edge_label next_node next_node_label
 *     [LADJ edge_label back_node edge_label back_node ... RADJ]]...
 *   [RESET node_x node_label_x ...]... EOS
 */

import type {
  AtomElement,
  AtomInfo,
  BondInfo,
  BondTypeName,
  MoleculeData,
} from './types';
import { ATOM_TYPES, BOND_TYPE_NAMES } from './types';
import type { TokenizerConfig } from './tokenizer';

// ─── Token Constants ─────────────────────────────────────────────────────────

export const SENT = {
  SOS: 0,
  RESET: 1,
  LADJ: 2,
  RADJ: 3,
  EOS: 4,
  PAD: 5,
  IDX_OFFSET: 6,
} as const;

// ─── Config Factory ──────────────────────────────────────────────────────────

/**
 * Create SENT tokenizer config from exported tokenizer_config.json values.
 */
export function createSentTokenizerConfig(
  vocabSize: number,
  labeledGraph: boolean,
  numAtomTypes = 10,
  numBondTypes = 5,
): TokenizerConfig {
  const maxNumNodes = labeledGraph
    ? vocabSize - SENT.IDX_OFFSET - numAtomTypes - numBondTypes
    : vocabSize - SENT.IDX_OFFSET;

  return {
    tokenizerType: 'sent',
    vocabSize,
    labeledGraph,
    maxNumNodes,
    numAtomTypes,
    numBondTypes,
    idxOffset: SENT.IDX_OFFSET,
    nodeIdxOffset: SENT.IDX_OFFSET + maxNumNodes,
    edgeIdxOffset: SENT.IDX_OFFSET + maxNumNodes + numAtomTypes,
    sosTokenId: SENT.SOS,
    eosTokenId: SENT.EOS,
    padTokenId: SENT.PAD,
  };
}

// ─── Full Decode ─────────────────────────────────────────────────────────────

/**
 * Decode a SENT token sequence into a MoleculeData structure.
 *
 * Port of:
 *   - reconstruct_graph_from_labeled_sent() from sent_utils.pyx:326-395
 *   - get_graph_from_labeled_sent() from wrapper.py:83-109
 */
export function decodeSentTokens(
  tokens: number[],
  config: TokenizerConfig,
  moleculeId = 0,
): MoleculeData {
  // Strip SOS, EOS, PAD
  const filtered = tokens.filter(
    (t) => t !== SENT.SOS && t !== SENT.EOS && t !== SENT.PAD,
  );

  if (filtered.length === 0) {
    return emptySentMolecule(moleculeId, tokens);
  }

  // Step 1: Reconstruct raw edge_index, node_labels, edge_labels
  // (port of reconstruct_graph_from_labeled_sent)
  const { edgeIndex, rawNodeLabels, rawEdgeLabels } = config.labeledGraph
    ? reconstructLabeledSent(filtered, config)
    : reconstructUnlabeledSent(filtered, config);

  if (edgeIndex.length === 0) {
    // No edges found - might be a single node or empty
    const nodeLabels = processNodeLabels(rawNodeLabels, config);
    return buildSentMolecule([], nodeLabels, [], moleculeId, tokens);
  }

  // Step 2: Post-process (port of get_graph_from_labeled_sent wrapper)
  // Subtract offsets
  const idxOffset = config.idxOffset;
  const nodeIdxOff = config.nodeIdxOffset;
  const edgeIdxOff = config.edgeIdxOffset;

  // Find max node index to determine node count
  let maxNodeIdx = 0;
  for (const [src, dst] of edgeIndex) {
    maxNodeIdx = Math.max(maxNodeIdx, src, dst);
  }

  // Process node labels: slice from idxOffset to maxNodeIdx+1, subtract nodeIdxOffset
  const nodeLabels: number[] = [];
  for (let i = idxOffset; i <= maxNodeIdx; i++) {
    let label = (rawNodeLabels.get(i) ?? -1) - nodeIdxOff;
    if (label < 0 || label >= config.numAtomTypes) label = 0;
    nodeLabels.push(label);
  }

  // Process edges: subtract idxOffset, symmetrize, remove self-loops, coalesce
  const edges: [number, number][] = [];
  const edgeLabels: number[] = [];

  for (let i = 0; i < edgeIndex.length; i++) {
    const src = edgeIndex[i]![0] - idxOffset;
    const dst = edgeIndex[i]![1] - idxOffset;
    let label = (rawEdgeLabels[i] ?? -1) - edgeIdxOff;
    if (label < 0 || label >= config.numBondTypes) label = 0;

    // Skip self-loops
    if (src === dst) continue;
    // Skip out-of-range
    if (src < 0 || dst < 0) continue;

    // Add both directions (symmetrize)
    edges.push([src, dst]);
    edgeLabels.push(label);
    edges.push([dst, src]);
    edgeLabels.push(label);
  }

  // Coalesce: keep unique undirected edges with min label
  const coalescedEdges = coalesceEdges(edges, edgeLabels);

  return buildSentMolecule(coalescedEdges.edges, nodeLabels, coalescedEdges.labels, moleculeId, tokens);
}

// ─── Reconstruction (Labeled) ────────────────────────────────────────────────

/**
 * Port of reconstruct_graph_from_labeled_sent from sent_utils.pyx:326-395.
 *
 * Walks through the token sequence extracting edges, node labels, and edge labels.
 */
function reconstructLabeledSent(
  seq: number[],
  _config: TokenizerConfig,
): {
  edgeIndex: [number, number][];
  rawNodeLabels: Map<number, number>;
  rawEdgeLabels: number[];
} {
  const walkLen = seq.length;
  const edgeIndex: [number, number][] = [];
  const rawNodeLabels = new Map<number, number>();
  const rawEdgeLabels: number[] = [];

  let bracketIdx = 0;
  let startBracket = false;
  let i = 0;

  const resetIdx = SENT.RESET;
  const leftBracket = SENT.LADJ;
  const rightBracket = SENT.RADJ;

  while (i < walkLen - 1) {
    // RESET handling
    if (seq[i] === resetIdx || seq[i + 1] === resetIdx) {
      startBracket = false;
      i++;
      continue;
    }

    if (seq[i] === leftBracket) {
      // Start bracket block - bracket_idx is the node 2 positions back
      // (node, node_label, LADJ) so bracket_idx = seq[i-2]
      startBracket = true;
      bracketIdx = i >= 2 ? seq[i - 2]! : 0;
      i++;
    } else if (seq[i] === rightBracket && startBracket) {
      // End bracket - edge from bracketIdx to the next node (at i+2)
      // Pattern: RADJ edge_label next_node
      if (i + 2 < walkLen) {
        edgeIndex.push([bracketIdx, seq[i + 2]!]);
        rawEdgeLabels.push(seq[i + 1]!);
      }
      startBracket = false;
      i += 2;
    } else if (startBracket) {
      // Inside brackets: edge_label back_node pairs
      if (i + 1 < walkLen) {
        edgeIndex.push([bracketIdx, seq[i + 1]!]);
        rawEdgeLabels.push(seq[i]!);
      }
      i += 2;
    } else if (i + 2 < walkLen && seq[i + 2] === resetIdx) {
      // Node before RESET: just record label
      const nodeIdx = seq[i]!;
      if (!rawNodeLabels.has(nodeIdx)) {
        rawNodeLabels.set(nodeIdx, seq[i + 1]!);
      }
      i += 2;
    } else if (i + 2 < walkLen && seq[i + 2] === leftBracket) {
      // Node before bracket: just record label
      const nodeIdx = seq[i]!;
      if (!rawNodeLabels.has(nodeIdx)) {
        rawNodeLabels.set(nodeIdx, seq[i + 1]!);
      }
      i += 2;
    } else {
      // Normal forward edge: node node_label edge_label next_node
      const nodeIdx = seq[i]!;
      if (!rawNodeLabels.has(nodeIdx)) {
        rawNodeLabels.set(nodeIdx, seq[i + 1]!);
      }
      if (i + 3 <= walkLen - 1) {
        edgeIndex.push([nodeIdx, seq[i + 3]!]);
        rawEdgeLabels.push(seq[i + 2]!);
      }
      i += 3;
    }
  }

  // Handle last token's label if not yet recorded
  if (walkLen >= 2) {
    const lastNodeIdx = seq[walkLen - 2];
    const lastLabel = seq[walkLen - 1];
    if (lastNodeIdx !== undefined && lastLabel !== undefined &&
        lastNodeIdx !== resetIdx && lastNodeIdx !== leftBracket &&
        lastNodeIdx !== rightBracket &&
        !rawNodeLabels.has(lastNodeIdx)) {
      rawNodeLabels.set(lastNodeIdx, lastLabel);
    }
  }

  return { edgeIndex, rawNodeLabels, rawEdgeLabels };
}

// ─── Reconstruction (Unlabeled) ──────────────────────────────────────────────

/**
 * Port of reconstruct_graph_from_sent from sent_utils.pyx:283-323.
 */
function reconstructUnlabeledSent(
  seq: number[],
  _config: TokenizerConfig,
): {
  edgeIndex: [number, number][];
  rawNodeLabels: Map<number, number>;
  rawEdgeLabels: number[];
} {
  const walkLen = seq.length;
  const edgeIndex: [number, number][] = [];
  const rawNodeLabels = new Map<number, number>();
  const rawEdgeLabels: number[] = [];

  const resetIdx = SENT.RESET;
  const leftBracket = SENT.LADJ;
  const rightBracket = SENT.RADJ;

  let bracketIdx = 0;
  let startBracket = false;

  for (let i = 0; i < walkLen - 1; i++) {
    if (seq[i] === resetIdx || seq[i + 1] === resetIdx || seq[i + 1] === leftBracket) {
      startBracket = false;
      continue;
    }
    if (seq[i] === leftBracket) {
      startBracket = true;
      bracketIdx = seq[i - 1]!;
    } else if (seq[i] === rightBracket && startBracket) {
      edgeIndex.push([bracketIdx, seq[i + 1]!]);
      rawEdgeLabels.push(0);
      startBracket = false;
    } else if (startBracket) {
      edgeIndex.push([bracketIdx, seq[i]!]);
      rawEdgeLabels.push(0);
    } else {
      edgeIndex.push([seq[i]!, seq[i + 1]!]);
      rawEdgeLabels.push(0);
    }
  }

  return { edgeIndex, rawNodeLabels, rawEdgeLabels };
}

// ─── Post-processing helpers ─────────────────────────────────────────────────

function processNodeLabels(
  rawLabels: Map<number, number>,
  config: TokenizerConfig,
): number[] {
  if (!config.labeledGraph || rawLabels.size === 0) return [];
  const nodeIdxOff = config.nodeIdxOffset;
  const result: number[] = [];
  // Determine range from labels
  const allKeys = [...rawLabels.keys()];
  const minKey = Math.min(...allKeys);
  const maxKey = Math.max(...allKeys);
  for (let i = minKey; i <= maxKey; i++) {
    let label = (rawLabels.get(i) ?? -1) - nodeIdxOff;
    if (label < 0 || label >= config.numAtomTypes) label = 0;
    result.push(label);
  }
  return result;
}

/**
 * Coalesce edges: keep unique undirected edges with minimum label.
 */
function coalesceEdges(
  edges: [number, number][],
  labels: number[],
): { edges: [number, number][]; labels: number[] } {
  const edgeMap = new Map<string, { src: number; dst: number; label: number }>();

  for (let i = 0; i < edges.length; i++) {
    const [src, dst] = edges[i]!;
    const key = src < dst ? `${src}-${dst}` : `${dst}-${src}`;
    const existing = edgeMap.get(key);
    if (!existing || labels[i]! < existing.label) {
      edgeMap.set(key, { src: Math.min(src, dst), dst: Math.max(src, dst), label: labels[i]! });
    }
  }

  const resultEdges: [number, number][] = [];
  const resultLabels: number[] = [];
  for (const { src, dst, label } of edgeMap.values()) {
    resultEdges.push([src, dst]);
    resultLabels.push(label);
  }

  return { edges: resultEdges, labels: resultLabels };
}

// ─── Build MoleculeData ──────────────────────────────────────────────────────

function buildSentMolecule(
  edges: [number, number][],
  nodeLabels: number[],
  edgeLabels: number[],
  moleculeId: number,
  tokens: number[],
): MoleculeData {
  // Collect all atom indices
  const atomSet = new Set<number>();
  for (const [src, dst] of edges) {
    atomSet.add(src);
    atomSet.add(dst);
  }
  // Also add nodes from nodeLabels (even if they have no edges)
  for (let i = 0; i < nodeLabels.length; i++) {
    atomSet.add(i);
  }

  const numAtoms = atomSet.size > 0 ? Math.max(...atomSet) + 1 : nodeLabels.length;

  // Build atoms array
  const atoms: AtomInfo[] = [];
  for (let i = 0; i < numAtoms; i++) {
    if (!atomSet.has(i) && i >= nodeLabels.length) continue;
    const typeIdx = i < nodeLabels.length ? nodeLabels[i]! : 0;
    const element: AtomElement =
      typeIdx < ATOM_TYPES.length ? ATOM_TYPES[typeIdx]! : 'Unknown';
    atoms.push({
      index: i,
      element,
      typeIdx,
      x: 0,
      y: 0,
      z: 0,
      communityId: -1, // SENT has no communities
    });
  }

  // Build bonds array
  const bonds: BondInfo[] = [];
  for (let i = 0; i < edges.length; i++) {
    const [src, dst] = edges[i]!;
    const typeIdx = edgeLabels[i] ?? 0;
    const typeName: BondTypeName =
      typeIdx < BOND_TYPE_NAMES.length ? BOND_TYPE_NAMES[typeIdx]! : 'Unknown';
    bonds.push({ src, dst, typeIdx, typeName });
  }

  return {
    id: moleculeId,
    communities: [], // SENT has no communities
    superEdges: [],  // SENT has no super-graph
    atoms,
    bonds,
    smiles: null,
    isValid: atoms.length > 0,
    tokens,
    numAtoms: atoms.length,
  };
}

function emptySentMolecule(id: number, tokens: number[]): MoleculeData {
  return {
    id,
    communities: [],
    superEdges: [],
    atoms: [],
    bonds: [],
    smiles: null,
    isValid: false,
    tokens,
    numAtoms: 0,
  };
}

/** Human-readable SENT token string for debugging. */
export function sentTokenToString(token: number, config: TokenizerConfig): string {
  const names: Record<number, string> = {
    [SENT.SOS]: 'SOS',
    [SENT.RESET]: 'RESET',
    [SENT.LADJ]: 'LADJ',
    [SENT.RADJ]: 'RADJ',
    [SENT.EOS]: 'EOS',
    [SENT.PAD]: 'PAD',
  };

  if (token in names) return names[token]!;

  if (config.labeledGraph && token >= config.edgeIdxOffset) {
    const bondIdx = token - config.edgeIdxOffset;
    return `BOND:${BOND_TYPE_NAMES[bondIdx] ?? bondIdx}`;
  }
  if (config.labeledGraph && token >= config.nodeIdxOffset) {
    const atomIdx = token - config.nodeIdxOffset;
    return `ATOM:${ATOM_TYPES[atomIdx] ?? atomIdx}`;
  }
  if (token >= SENT.IDX_OFFSET) {
    return `N${token - SENT.IDX_OFFSET}`;
  }

  return `?${token}`;
}
