/**
 * HDTC Tokenizer - TypeScript port of src/tokenizers/hdtc/tokenizer.py decode logic.
 *
 * Decodes token sequences generated by the MOSAIC GPT-2 model back into
 * molecular graph structures (communities, atoms, bonds, super-edges).
 *
 * Token vocabulary:
 *   0: SOS, 1: EOS, 2: PAD
 *   3: COMM_START, 4: COMM_END
 *   5: LEDGE, 6: REDGE
 *   7: SUPER_START, 8: SUPER_END
 *   9: TYPE_RING, 10: TYPE_FUNC, 11: TYPE_SINGLETON
 *   12+: Node indices (offset by IDX_OFFSET)
 *
 * For labeled graphs, vocab layout:
 *   [special (12)] + [node IDs (max_num_nodes)] + [atom types (10)] + [bond types (5)]
 */

import type {
  AtomElement,
  AtomInfo,
  BondInfo,
  BondTypeName,
  Community,
  CommunityType,
  MoleculeData,
  SuperEdge,
} from './types';
import { ATOM_TYPES, BOND_TYPE_NAMES } from './types';

// ─── Token Constants ─────────────────────────────────────────────────────────

export const HDTC = {
  SOS: 0,
  EOS: 1,
  PAD: 2,
  COMM_START: 3,
  COMM_END: 4,
  LEDGE: 5,
  REDGE: 6,
  SUPER_START: 7,
  SUPER_END: 8,
  TYPE_RING: 9,
  TYPE_FUNC: 10,
  TYPE_SINGLETON: 11,
  IDX_OFFSET: 12,
} as const;

const TOKEN_TO_COMMUNITY_TYPE: Record<number, CommunityType> = {
  [HDTC.TYPE_RING]: 'ring',
  [HDTC.TYPE_FUNC]: 'functional',
  [HDTC.TYPE_SINGLETON]: 'singleton',
};

// ─── Tokenizer Config ────────────────────────────────────────────────────────

export interface TokenizerConfig {
  vocabSize: number;
  labeledGraph: boolean;
  maxNumNodes: number;
  numAtomTypes: number;  // 10
  numBondTypes: number;  // 5
  /** IDX_OFFSET + maxNumNodes (start of atom type tokens) */
  nodeIdxOffset: number;
  /** nodeIdxOffset + numAtomTypes (start of bond type tokens) */
  edgeIdxOffset: number;
}

/**
 * Create tokenizer config from exported tokenizer_config.json values.
 */
export function createTokenizerConfig(
  vocabSize: number,
  labeledGraph: boolean,
  numAtomTypes = 10,
  numBondTypes = 5,
): TokenizerConfig {
  const maxNumNodes = labeledGraph
    ? vocabSize - HDTC.IDX_OFFSET - numAtomTypes - numBondTypes
    : vocabSize - HDTC.IDX_OFFSET;

  return {
    vocabSize,
    labeledGraph,
    maxNumNodes,
    numAtomTypes,
    numBondTypes,
    nodeIdxOffset: HDTC.IDX_OFFSET + maxNumNodes,
    edgeIdxOffset: HDTC.IDX_OFFSET + maxNumNodes + numAtomTypes,
  };
}

// ─── Full Decode ─────────────────────────────────────────────────────────────

/**
 * Decode a token sequence into a MoleculeData structure.
 *
 * Port of HDTCTokenizer.parse_tokens() from tokenizer.py:471-537.
 */
export function decodeTokens(
  tokens: number[],
  config: TokenizerConfig,
  moleculeId = 0,
): MoleculeData {
  // Strip SOS, EOS, PAD
  const filtered = tokens.filter(
    (t) => t !== HDTC.SOS && t !== HDTC.EOS && t !== HDTC.PAD,
  );

  if (filtered.length === 0) {
    return emptyMolecule(moleculeId);
  }

  const communities: Community[] = [];
  const superEdges: SuperEdge[] = [];
  const allAtoms = new Set<number>();
  const allEdges: [number, number][] = [];
  const nodeFeatures = new Map<number, number>();
  const edgeFeatures = new Map<string, number>();

  let idx = 0;
  while (idx < filtered.length) {
    const tok = filtered[idx]!;

    if (tok === HDTC.COMM_START) {
      const result = parseCommunity(
        filtered, idx, config, allAtoms, allEdges, nodeFeatures, edgeFeatures,
      );
      if (result.community) {
        communities.push(result.community);
      }
      idx = result.nextIdx;
    } else if (tok === HDTC.SUPER_START) {
      const result = parseSuperGraph(filtered, idx, config);
      superEdges.push(...result.superEdges);
      // Add super-edge atom-level bonds to allEdges (inter-community connections)
      for (const se of result.superEdges) {
        allAtoms.add(se.sourceAtom);
        allAtoms.add(se.targetAtom);
        allEdges.push([se.sourceAtom, se.targetAtom]);
        allEdges.push([se.targetAtom, se.sourceAtom]);
      }
      idx = result.nextIdx;
    } else {
      idx++;
    }
  }

  // Build atom-to-community mapping
  const atomToCommunity = new Map<number, number>();
  for (const comm of communities) {
    for (const atomIdx of comm.atomIndices) {
      atomToCommunity.set(atomIdx, comm.id);
    }
  }

  // Build atoms array
  const numAtoms = allAtoms.size > 0 ? Math.max(...allAtoms) + 1 : 0;
  const atoms: AtomInfo[] = [];
  for (let i = 0; i < numAtoms; i++) {
    if (!allAtoms.has(i)) continue;
    const typeIdx = nodeFeatures.get(i) ?? 0;
    const element: AtomElement =
      typeIdx < ATOM_TYPES.length ? ATOM_TYPES[typeIdx]! : 'Unknown';
    atoms.push({
      index: i,
      element,
      typeIdx,
      x: 0,
      y: 0,
      z: 0,
      communityId: atomToCommunity.get(i) ?? -1,
    });
  }

  // Build bonds array (deduplicate undirected edges)
  const bondSet = new Set<string>();
  const bonds: BondInfo[] = [];
  for (const [src, dst] of allEdges) {
    const key = src < dst ? `${src}-${dst}` : `${dst}-${src}`;
    if (bondSet.has(key)) continue;
    bondSet.add(key);
    const typeIdx =
      edgeFeatures.get(`${src}-${dst}`) ??
      edgeFeatures.get(`${dst}-${src}`) ??
      0;
    const typeName: BondTypeName =
      typeIdx < BOND_TYPE_NAMES.length ? BOND_TYPE_NAMES[typeIdx]! : 'Unknown';
    bonds.push({ src: Math.min(src, dst), dst: Math.max(src, dst), typeIdx, typeName });
  }

  return {
    id: moleculeId,
    communities,
    superEdges,
    atoms,
    bonds,
    smiles: null, // Will be filled by chemistry.ts
    isValid: atoms.length > 0,
    tokens,
    numAtoms: atoms.length,
  };
}

// ─── Community Parser ────────────────────────────────────────────────────────

/**
 * Parse a community block: COMM_START TYPE <comm_id> <atoms...> COMM_END
 *
 * Port of HDTCTokenizer._parse_community() from tokenizer.py:539-679.
 */
function parseCommunity(
  tokens: number[],
  startIdx: number,
  config: TokenizerConfig,
  allAtoms: Set<number>,
  allEdges: [number, number][],
  nodeFeatures: Map<number, number>,
  edgeFeatures: Map<string, number>,
): { community: Community | null; nextIdx: number } {
  let idx = startIdx;

  if (tokens[idx] !== HDTC.COMM_START) {
    return { community: null, nextIdx: idx };
  }
  idx++; // Skip COMM_START

  // Parse community type
  if (idx >= tokens.length) {
    return { community: null, nextIdx: idx };
  }
  const typeToken = tokens[idx]!;
  const communityType: CommunityType =
    TOKEN_TO_COMMUNITY_TYPE[typeToken] ?? 'singleton';
  idx++;

  // Parse community ID
  if (idx >= tokens.length || tokens[idx]! < HDTC.IDX_OFFSET) {
    return { community: null, nextIdx: idx };
  }
  const communityId = tokens[idx]! - HDTC.IDX_OFFSET;
  idx++;

  // Parse atoms and back-edges
  const atomIndices: number[] = [];
  const internalEdges: [number, number][] = [];
  const commNodeFeatures: number[] = [];
  let currentAtom: number | null = null;

  while (idx < tokens.length && tokens[idx] !== HDTC.COMM_END) {
    const tok = tokens[idx]!;

    if (tok >= HDTC.IDX_OFFSET) {
      // Distinguish node ID vs atom type vs bond type
      if (config.labeledGraph && tok >= config.edgeIdxOffset) {
        // Bond type token (skip - handled in LEDGE block)
        idx++;
      } else if (config.labeledGraph && tok >= config.nodeIdxOffset) {
        // Atom type token
        if (currentAtom !== null) {
          const atomType = tok - config.nodeIdxOffset;
          nodeFeatures.set(currentAtom, atomType);
          commNodeFeatures.push(atomType);
        }
        idx++;
      } else {
        // Node ID
        const atomIdx = tok - HDTC.IDX_OFFSET;
        atomIndices.push(atomIdx);
        allAtoms.add(atomIdx);
        currentAtom = atomIdx;
        idx++;
      }
    } else if (tok === HDTC.LEDGE) {
      // Back-edge block: LEDGE <targets...> REDGE
      idx++;
      while (idx < tokens.length && tokens[idx] !== HDTC.REDGE) {
        const edgeTok = tokens[idx]!;

        if (edgeTok >= HDTC.IDX_OFFSET) {
          if (config.labeledGraph && edgeTok >= config.edgeIdxOffset) {
            // Bond type token - skip (already handled)
            idx++;
          } else if (config.labeledGraph && edgeTok >= config.nodeIdxOffset) {
            // Atom type in wrong place - skip
            idx++;
          } else {
            // Target node
            const target = edgeTok - HDTC.IDX_OFFSET;
            if (currentAtom !== null) {
              internalEdges.push([currentAtom, target]);
              internalEdges.push([target, currentAtom]);
              allEdges.push([currentAtom, target]);
              allEdges.push([target, currentAtom]);

              // Check for bond type following target
              idx++;
              if (config.labeledGraph) {
                if (idx < tokens.length && tokens[idx]! >= config.edgeIdxOffset) {
                  const bondType = tokens[idx]! - config.edgeIdxOffset;
                  edgeFeatures.set(`${currentAtom}-${target}`, bondType);
                  edgeFeatures.set(`${target}-${currentAtom}`, bondType);
                  idx++;
                }
              }
            } else {
              idx++;
            }
          }
        } else {
          idx++;
        }
      }
      idx++; // Skip REDGE
    } else {
      idx++;
    }
  }

  // Skip COMM_END
  if (idx < tokens.length && tokens[idx] === HDTC.COMM_END) {
    idx++;
  }

  return {
    community: {
      id: communityId,
      type: communityType,
      atomIndices,
      internalEdges,
      nodeFeatures: commNodeFeatures.length > 0 ? commNodeFeatures : undefined,
    },
    nextIdx: idx,
  };
}

// ─── Super-Graph Parser ──────────────────────────────────────────────────────

/**
 * Parse super-graph block: SUPER_START [<src_comm> <dst_comm> <src_atom> <dst_atom>]* SUPER_END
 *
 * Port of HDTCTokenizer._parse_super_graph() from tokenizer.py:681-726.
 */
function parseSuperGraph(
  tokens: number[],
  startIdx: number,
  _config: TokenizerConfig,
): { superEdges: SuperEdge[]; nextIdx: number } {
  let idx = startIdx;

  if (tokens[idx] !== HDTC.SUPER_START) {
    return { superEdges: [], nextIdx: idx };
  }
  idx++; // Skip SUPER_START

  const superEdges: SuperEdge[] = [];

  while (idx + 3 < tokens.length && tokens[idx] !== HDTC.SUPER_END) {
    if (tokens[idx]! >= HDTC.IDX_OFFSET) {
      const srcComm = tokens[idx]! - HDTC.IDX_OFFSET;
      const dstComm = tokens[idx + 1]! - HDTC.IDX_OFFSET;
      const srcAtom = tokens[idx + 2]! - HDTC.IDX_OFFSET;
      const dstAtom = tokens[idx + 3]! - HDTC.IDX_OFFSET;

      superEdges.push({
        sourceCommunity: srcComm,
        targetCommunity: dstComm,
        sourceAtom: srcAtom,
        targetAtom: dstAtom,
      });
      idx += 4;
    } else {
      idx++;
    }
  }

  // Skip SUPER_END
  if (idx < tokens.length && tokens[idx] === HDTC.SUPER_END) {
    idx++;
  }

  return { superEdges, nextIdx: idx };
}

// ─── Partial Decode (for animation) ─────────────────────────────────────────

/**
 * State of a partially decoded molecule (token-by-token for animation).
 */
export interface PartialDecodeState {
  /** Communities fully parsed so far. */
  communities: Community[];
  /** Community currently being built (between COMM_START and COMM_END). */
  currentCommunity: Partial<Community> | null;
  /** Super-edges parsed so far. */
  superEdges: SuperEdge[];
  /** All atom indices seen so far. */
  atomsSeen: Set<number>;
  /** All edges seen so far (undirected, both directions). */
  edgesSeen: [number, number][];
  /** Node features map. */
  nodeFeatures: Map<number, number>;
  /** Edge features map. */
  edgeFeatures: Map<string, number>;
  /** Whether we're inside a super-graph block. */
  inSuperBlock: boolean;
  /** Whether we're inside a back-edge block. */
  inEdgeBlock: boolean;
  /** Current atom being processed. */
  currentAtom: number | null;
  /** Tokens accumulated in current super-graph parse (groups of 4). */
  superTokenBuffer: number[];
  /** Current community type token. */
  pendingType: CommunityType | null;
  /** Current community ID. */
  pendingCommId: number | null;
  /** Last back-edge target (for bond type assignment). */
  lastEdgeTarget: number | null;
}

/**
 * Create initial partial decode state.
 */
export function createPartialState(): PartialDecodeState {
  return {
    communities: [],
    currentCommunity: null,
    superEdges: [],
    atomsSeen: new Set(),
    edgesSeen: [],
    nodeFeatures: new Map(),
    edgeFeatures: new Map(),
    inSuperBlock: false,
    inEdgeBlock: false,
    currentAtom: null,
    superTokenBuffer: [],
    pendingType: null,
    pendingCommId: null,
    lastEdgeTarget: null,
  };
}

/**
 * Feed a single token to the partial decoder.
 *
 * Used for progressive animation during autoregressive generation.
 */
export function feedToken(
  state: PartialDecodeState,
  token: number,
  config: TokenizerConfig,
): void {
  // Skip special non-structural tokens
  if (token === HDTC.SOS || token === HDTC.PAD) return;
  if (token === HDTC.EOS) return;

  if (state.inSuperBlock) {
    feedTokenSuperBlock(state, token);
    return;
  }

  switch (token) {
    case HDTC.COMM_START:
      state.currentCommunity = {
        atomIndices: [],
        internalEdges: [],
      };
      state.pendingType = null;
      state.pendingCommId = null;
      state.currentAtom = null;
      break;

    case HDTC.COMM_END:
      if (state.currentCommunity) {
        const comm: Community = {
          id: state.pendingCommId ?? state.communities.length,
          type: state.pendingType ?? 'singleton',
          atomIndices: state.currentCommunity.atomIndices ?? [],
          internalEdges: (state.currentCommunity.internalEdges ?? []) as [number, number][],
        };
        state.communities.push(comm);
        state.currentCommunity = null;
      }
      break;

    case HDTC.LEDGE:
      state.inEdgeBlock = true;
      state.lastEdgeTarget = null;
      break;

    case HDTC.REDGE:
      state.inEdgeBlock = false;
      state.lastEdgeTarget = null;
      break;

    case HDTC.SUPER_START:
      state.inSuperBlock = true;
      state.superTokenBuffer = [];
      break;

    case HDTC.TYPE_RING:
    case HDTC.TYPE_FUNC:
    case HDTC.TYPE_SINGLETON:
      state.pendingType = TOKEN_TO_COMMUNITY_TYPE[token] ?? 'singleton';
      break;

    default:
      if (token >= HDTC.IDX_OFFSET) {
        feedTokenValue(state, token, config);
      }
      break;
  }
}

function feedTokenValue(
  state: PartialDecodeState,
  token: number,
  config: TokenizerConfig,
): void {
  if (!state.currentCommunity) return;

  if (config.labeledGraph && token >= config.edgeIdxOffset) {
    // Bond type token - assign to most recent back-edge
    if (state.inEdgeBlock && state.currentAtom !== null && state.lastEdgeTarget !== null) {
      const bondType = token - config.edgeIdxOffset;
      const src = state.currentAtom;
      const tgt = state.lastEdgeTarget;
      state.edgeFeatures.set(`${src}-${tgt}`, bondType);
      state.edgeFeatures.set(`${tgt}-${src}`, bondType);
      state.lastEdgeTarget = null;
    }
    return;
  }

  if (config.labeledGraph && token >= config.nodeIdxOffset) {
    // Atom type token
    if (state.currentAtom !== null) {
      state.nodeFeatures.set(state.currentAtom, token - config.nodeIdxOffset);
    }
    return;
  }

  // Node ID
  const nodeIdx = token - HDTC.IDX_OFFSET;

  if (state.pendingCommId === null && !state.currentCommunity.atomIndices?.length) {
    // First value token after type - this is the community ID
    state.pendingCommId = nodeIdx;
    return;
  }

  if (state.inEdgeBlock) {
    // This is a back-edge target
    if (state.currentAtom !== null) {
      const edges = state.currentCommunity.internalEdges as [number, number][] ?? [];
      edges.push([state.currentAtom, nodeIdx]);
      edges.push([nodeIdx, state.currentAtom]);
      state.currentCommunity.internalEdges = edges;
      state.edgesSeen.push([state.currentAtom, nodeIdx]);
      state.edgesSeen.push([nodeIdx, state.currentAtom]);
      state.lastEdgeTarget = nodeIdx;
    }
  } else {
    // New atom in community
    const atoms = state.currentCommunity.atomIndices ?? [];
    atoms.push(nodeIdx);
    state.currentCommunity.atomIndices = atoms;
    state.atomsSeen.add(nodeIdx);
    state.currentAtom = nodeIdx;
  }
}

function feedTokenSuperBlock(state: PartialDecodeState, token: number): void {
  if (token === HDTC.SUPER_END) {
    state.inSuperBlock = false;
    return;
  }

  if (token >= HDTC.IDX_OFFSET) {
    state.superTokenBuffer.push(token - HDTC.IDX_OFFSET);

    if (state.superTokenBuffer.length === 4) {
      const se: SuperEdge = {
        sourceCommunity: state.superTokenBuffer[0]!,
        targetCommunity: state.superTokenBuffer[1]!,
        sourceAtom: state.superTokenBuffer[2]!,
        targetAtom: state.superTokenBuffer[3]!,
      };
      state.superEdges.push(se);
      // Add inter-community atom bonds to edges/atoms
      state.atomsSeen.add(se.sourceAtom);
      state.atomsSeen.add(se.targetAtom);
      state.edgesSeen.push([se.sourceAtom, se.targetAtom]);
      state.edgesSeen.push([se.targetAtom, se.sourceAtom]);
      state.superTokenBuffer = [];
    }
  }
}

/**
 * Convert partial state to a snapshot MoleculeData (for rendering mid-generation).
 */
export function stateToMolecule(
  state: PartialDecodeState,
  _config: TokenizerConfig,
  moleculeId = 0,
): MoleculeData {
  // Include completed communities + current partial one
  const communities = [...state.communities];
  if (state.currentCommunity && state.currentCommunity.atomIndices?.length) {
    communities.push({
      id: state.pendingCommId ?? communities.length,
      type: state.pendingType ?? 'singleton',
      atomIndices: state.currentCommunity.atomIndices,
      internalEdges: (state.currentCommunity.internalEdges ?? []) as [number, number][],
    });
  }

  // Build atom-to-community mapping
  const atomToCommunity = new Map<number, number>();
  for (const comm of communities) {
    for (const atomIdx of comm.atomIndices) {
      atomToCommunity.set(atomIdx, comm.id);
    }
  }

  // Build atoms
  const atoms: AtomInfo[] = [];
  for (const atomIdx of state.atomsSeen) {
    const typeIdx = state.nodeFeatures.get(atomIdx) ?? 0;
    const element: AtomElement =
      typeIdx < ATOM_TYPES.length ? ATOM_TYPES[typeIdx]! : 'Unknown';
    atoms.push({
      index: atomIdx,
      element,
      typeIdx,
      x: 0, y: 0, z: 0,
      communityId: atomToCommunity.get(atomIdx) ?? -1,
    });
  }

  // Build bonds (deduplicated)
  const bondSet = new Set<string>();
  const bonds: BondInfo[] = [];
  for (const [src, dst] of state.edgesSeen) {
    const key = src < dst ? `${src}-${dst}` : `${dst}-${src}`;
    if (bondSet.has(key)) continue;
    bondSet.add(key);
    const typeIdx =
      state.edgeFeatures.get(`${src}-${dst}`) ??
      state.edgeFeatures.get(`${dst}-${src}`) ??
      0;
    const typeName: BondTypeName =
      typeIdx < BOND_TYPE_NAMES.length ? BOND_TYPE_NAMES[typeIdx]! : 'Unknown';
    bonds.push({ src: Math.min(src, dst), dst: Math.max(src, dst), typeIdx, typeName });
  }

  return {
    id: moleculeId,
    communities,
    superEdges: [...state.superEdges],
    atoms,
    bonds,
    smiles: null,
    isValid: atoms.length > 0,
    tokens: [],
    numAtoms: atoms.length,
  };
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function emptyMolecule(id: number): MoleculeData {
  return {
    id,
    communities: [],
    superEdges: [],
    atoms: [],
    bonds: [],
    smiles: null,
    isValid: false,
    tokens: [],
    numAtoms: 0,
  };
}

/** Human-readable token string for debugging. */
export function tokenToString(token: number, config: TokenizerConfig): string {
  const names: Record<number, string> = {
    [HDTC.SOS]: 'SOS',
    [HDTC.EOS]: 'EOS',
    [HDTC.PAD]: 'PAD',
    [HDTC.COMM_START]: 'COMM_START',
    [HDTC.COMM_END]: 'COMM_END',
    [HDTC.LEDGE]: 'LEDGE',
    [HDTC.REDGE]: 'REDGE',
    [HDTC.SUPER_START]: 'SUPER_START',
    [HDTC.SUPER_END]: 'SUPER_END',
    [HDTC.TYPE_RING]: 'TYPE_RING',
    [HDTC.TYPE_FUNC]: 'TYPE_FUNC',
    [HDTC.TYPE_SINGLETON]: 'TYPE_SINGLETON',
  };

  if (token in names) return names[token]!;

  if (config.labeledGraph && token >= config.edgeIdxOffset) {
    const bondIdx = token - config.edgeIdxOffset;
    return `BOND:${BOND_TYPE_NAMES[bondIdx] ?? bondIdx}`;
  }
  if (config.labeledGraph && token >= config.nodeIdxOffset) {
    const atomIdx = token - config.nodeIdxOffset;
    return `ATOM:${ATOM_TYPES[atomIdx] ?? atomIdx}`;
  }
  if (token >= HDTC.IDX_OFFSET) {
    return `N${token - HDTC.IDX_OFFSET}`;
  }

  return `?${token}`;
}
